# Generated by Django 4.0.4 on 2022-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_remove_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', through='levelupapi.EventGamer', to='levelupapi.gamer'),
        ),
    ]
